### ISSUE TITLE
Could you provide a Java binding?

### ISSUE THREAD

**Issue by ghost** [mozilla-spidermonkey/spidermonkey-embedding-examples#39]
All of the examples deal with C/C++ only. What about embedding in Java based application? It's much better if you could provide a Java wrapper. Thanks.

**Comment by mgaudet** [comment]
Providing a Java binding is probably possible, but would be a large engineering effort (and require some custom code to handle things object lifetime). 

While an interesting proposal, I don't see it being something we'll jump on any time soon. You may be better served by embedding a JS engine that's native to Java, like GraalJS or Nashorn.

**Comment by mgaudet** [comment]
Also, apparently Rhino is also being maintained :)

**Comment by ghost** [comment]
> Providing a Java binding is probably possible, but would be a large engineering effort (and require some custom code to handle things object lifetime).
> 
> While an interesting proposal, I don't see it being something we'll jump on any time soon. You may be better served by embedding a JS engine that's native to Java, like GraalJS or Nashorn.

We stuck with Java 8 so, no, GraalVM is not an option.
Nashorn was no longer being developed for a long time.

**Comment by ghost** [comment]
> Also, apparently Rhino is also being maintained :)

Not an option. Not even supports classes. Seems lack of maintenance indeed, of course no longer active developed!

https://github.com/mozilla/rhino/issues/524

**Comment by ghost** [comment]
You guys being at Mozilla too please ask them to put some more love into Rhino. If it's not the organization's focus please mark Rhino as deprecated like Oracle did with Nashorn. The page of Rhino at Mozilla is being archived and read only. Even though not explicitly announced that they no longer developed Rhino and put it to the community to maintain like Microsoft did with ChakraCore, the current state of Rhino is not any better than ChakraCore.

https://github.com/chakra-core/ChakraCore
