### ISSUE TITLE
Create ESR91 Branch

### ISSUE THREAD

**Issue by moztcampbell** [mozilla-spidermonkey/spidermonkey-embedding-examples#41]
After ESR71 merges to beta next week, we should update the 'next' branch for the final small changes (eg. PrintError) and then spin out the ESR71 branch. 

Also, I'd like to get https://bugzilla.mozilla.org/show_bug.cgi?id=1716147 and https://bugzilla.mozilla.org/show_bug.cgi?id=1711878 landed to fix windows builds.

**Comment by TheQwertiest** [comment]
maybe esr 91 and not 71? =)

**Comment by ewlsh** [comment]
This MR is tracking GJS' current mozjs91 migration and the changes needed - https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/632/commits

**Comment by moztcampbell** [comment]
I updated the 'next' branch in Issue #43 and added a few more notes to the Migration Guide. After that, I think it is just tweaking the CI files and making the branch.

**Comment by TheQwertiest** [comment]
It seems that SM build via `configure` was removed and now it can only be built via `mach`.
I.e. [this page](https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples/blob/next/docs/Building%20SpiderMonkey.md) needs to be updated or maybe replaced with [this one](https://firefox-source-docs.mozilla.org/js/build.html).

**Comment by TheQwertiest** [comment]
A few other changes that I've encountered during migration that are not listed (might be from 78esr though):
- `JS_SetGCParameter( cx, JSGC_MODE, JSGC_MODE_INCREMENTAL )` > `JS_SetGCParameter( cx, JSGC_INCREMENTAL_GC_ENABLED, 1 );`

- `JSID_{IS/GET}_SYMBOL()` > `id.{is/get}Symbol()`

- New undocumented `mutedErrors` argument in Promise handler 
  [EDIT] clarification: documented in migration guide, but not in header.

**Comment by lostnet** [comment]
The polkit MR is here: [https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/92](https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/92)

I think ~moz83+ being pedantic about JS_Init/JS_Shutdown is of particular relevance to the guide [https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/91](https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/91) as other integrations such as couchdb's also don't call JS_Shutdown correctly.

**Comment by ptomato** [comment]
Thanks, I added a note about this to https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples/pull/46

**Comment by ptomato** [comment]
I pushed a copy of the `next` branch as `esr91`, could someone with settings access make it the default branch please? After that, this issue can be closed, I think.

Also see #48

**Comment by jandem** [comment]
> I pushed a copy of the `next` branch as `esr91`, could someone with settings access make it the default branch please? After that, this issue can be closed, I think.

Done! Thanks for working on this.

**Comment by MagicalDrizzle** [comment]
It seems the examples in the doc directory stills say to use ./configure?

**Comment by ptomato** [comment]
That is still how many embedders build SpiderMonkey, even though I understand it is no longer recommended for developing Firefox.
