### ISSUE TITLE
Bring back the plain C API header

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [mozilla-spidermonkey/spidermonkey-embedding-examples#69]
It used to be a time I could call it from a plain C application. Now everything is C++.

**Comment by jandem** [comment]
Thanks for the bug report.

Modern SpiderMonkey code relies heavily on C++ RAII classes (for stack rooting, vectors, hash maps, etc). Writing a C header would be tedious and is very unlikely to happen at this point. If anyone is willing to maintain a C wrapper out of tree, we'd love to hear about it though.
